# !Bienvenid@s! 游녦 {.unnumbered}
<hr/>

Este manual lleva por t칤tulo *"Mapeo de Erosi칩n del Suelo a Nivel Nacional empleando la Metodolog칤a RUSLE y rgee"*. **El objetivo, de esta gu칤a dar a conocer a los usuarios y nuevos usuarios un flujo de trabajo reproducible y replicable para cualquier 치rea de estudio que desea estimar y analizar los patrones espaciales y temporales de la erosi칩n de suelo**.

Bajo el conexto de la ciencia datos y el apogeo de la mineria de datos (**big data** o **data mining**), esta gu칤a dar치 a conocer el f치cil acceso y procesamientos automatico de datos geogr치ficos (**geocomputaci칩n o geograf칤a computacional**) que permitan su manipulaci칩n para el c치lculo de la erosi칩n del suelo sin tener la necesidad de contar con elevadas capacidades computacionales.

Finalmente, para poder reproducir y replicar satisfactoriamente este manual se debe tener cierto acercamiento a cualquier lenguaje de programaci칩n orientado a objetos (**R**,**python**, **JavaScript**, **etc**), asimismo se dar치 ciertas requerimientos que deber치 presentar tu laptop o pc para la instalaci칩n de software con el fin de cumplir los objetivos mostrados inicialmente, es necesario recalcar que todo los procesos que se dar치n a conocer en los pr칩ximos c치pitulos ser치n desarrollado s칩lo bajo el lenguaje de    programaci칩n de **R**. 